let hey = document.getElementById("hey")
console.log(hey.getAttribute("class"))
console.log(hey.hasAttribute("class"))
console.log(hey.hasAttribute("class"))
console.log(hey.hasAttribute("id"))
console.log(hey.hasAttribute("style"))
// console.log(hey.setAttribute("hidden","true"))
// console.log(hey.setAttribute("class","hii"))
// console.log(hey.removeAttribute("class"))
console.log(hey.attributes)
console.log(hey.dataset)
console.log(hey.dataset.name)
console.log(hey.dataset.cast)
